openapi: "3.0.3"
info:
  title: "BeamBorg API"
  version: "0.1.0"
paths:
  /session/new:
    post:
      description: "Creates a new beam session"
      responses:
        "201":
          description: "Created"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BeamSession"
  /session/{id}:
    get:
      description: "Returns a customer by its ID"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BeamSession"
    patch:
      description: "Patch a customer by its ID"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
      requestBody:
        description: "A JSON object containing session content"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BeamSessionUpdate"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BeamSession"
components:
  schemas:
    BeamSession:
      type: "object"
      required: ["id"]
      properties:
        id:
          type: "string"
        content:
          type: "string"
    BeamSessionUpdate:
      type: "object"
      required: [ "content" ]
      properties:
        content:
          type: "string"