openapi: "3.0.3"
info:
  title: "Breeze API"
  version: "0.1.0"
paths:
  /api/v1/session/new:
    post:
      responses:
        "201":
          description: "Created"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BeamSession"
  /api/v1/session/{id}:
    get:
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BeamSession"
  /api/v1/session/{id}/upload:
    post:
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                text:
                  type: string
                image:
                  type: string
                  format: binary
            encoding:
              image:
                contentType: image/png
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: string
                example: OK
components:
  schemas:
    BeamSession:
      type: "object"
      required: ["id"]
      properties:
        id:
          type: "string"
        type:
          type: "string"
        content:
          type: "string"
